apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: testchart
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: testchart
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: helmrepo
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
